package com.uoj.equipment.enums;

public enum NotificationType {

    REQUEST_SUBMITTED,
    REQUEST_APPROVED,
    REQUEST_REJECTED,

    ISSUE_READY,
    ISSUE_ACCEPTED,

    RETURN_SUBMITTED,
    RETURN_VERIFIED,
    DAMAGE_REPORTED,

    TO_WAIT,

    PURCHASE_SUBMITTED,
    PURCHASE_APPROVED_BY_HOD,
    PURCHASE_REJECTED_BY_HOD,
    PURCHASE_APPROVED_BY_ADMIN,
    PURCHASE_REJECTED_BY_ADMIN,
    PURCHASE_RECEIVED_BY_HOD       // HOD confirmed items received — TO notified, inventory updated
}